---
title: 'Infliximab: Time-Weighted Bayesian Estimation'
author: "Jessica Wojciechowski"
date: "7 July 2016"
output:
  html_document:
    fig_width: 10
    highlight: textmate
---

```{r,echo = FALSE,warning = FALSE}
# Remove all current objects in the workspace
	rm(list = ls(all = TRUE))
# Load package libraries
  library(ggplot2)  # Plotting
  library(grid)  # Plotting
  library(plyr)  # ddply function

# Custom ggplot2 theme
  theme_bw2 <- theme_set(theme_bw(base_size = 14))

# Pre-specified functions
  CI95lo <- function(x) quantile(x,probs = 0.025)  # Calculate 2.5th percentile
  CI95hi <- function(x) quantile(x,probs = 0.975)  # Calculate 97.5th percentile

# Summary function for calculating median and prediction intervals
  summary.function <- function(x) {
    median <- median(x)
    stat.95lo <- quantile(x,probs = 0.025)
    stat.95hi <- quantile(x,probs = 0.975)
    result <- c(median,stat.95lo,stat.95hi)
    names(result)[c(1,2,3)] <- c("median","stat.95lo","stat.95hi")
    result
  }

# Set trough target objects
  trough.target <- 3
  trough.upper <- 5

# ------------------------------------------------------------------------------
# Set working directory
  # project.dir <- "/Volumes/Prosecutor/PhD/InfliximabBayes/Moved-Infliximab-Output/" # Mac directory
  project.dir <- "E:/Wojciechowski/Moved-Infliximab-Output/"  # Server directory

# Read in simulation output
  file.list <- list.files(path = project.dir,pattern = "SUCCESS") # List of successful simulation sets
  n <- 9  # Number of seed individuals that were simulated
  nsim <- 10  # Number of simulations of seed individuals per set
  nset <- length(file.list)  # Number of simulation sets in the directory
  set.seq <- 1:nset  # Sequence of "set" numbers

# Read in the label simulation data
  read.label.data.function <- function(file.list) {
    label.data <- read.csv(file = paste0(project.dir,file.list,"/label_simulation.csv"))
  }
  label.data <- ldply(file.list,read.label.data.function)
  SET <- sort(c(rep(set.seq,times = dim(label.data)[1]/nset)))
  label.data$SET <- SET
  label.data$STUDY <- 1

# Read in the clinical simulation data
  read.clinical.data.function <- function(file.list) {
    clinical.data <- read.csv(file = paste0(project.dir,file.list,"/clinical_simulation.csv"))
  }
  clinical.data <- ldply(file.list,read.clinical.data.function)
  clinical.data$SET <- SET
  clinical.data$STUDY <- 2

# Read in the clinical_TDM simulation data
  read.clinical.TDM.data.function <- function(file.list) {
    clinical.TDM.data <- read.csv(file = paste0(project.dir,file.list,"/clinical_TDM_simulation.csv"))
  }
  clinical.TDM.data <- ldply(file.list,read.clinical.TDM.data.function)
  clinical.TDM.data$SET <- SET
  clinical.TDM.data$STUDY <- 3

# Read in the optimise.bayes1 simulation data (5 mg/kg initiation)
  read.optimise.bayes.data1 <- function(file.list) {
    optimise.bayes.data1 <- read.csv(file = paste0(project.dir,file.list,"/optimise_bayes_data1.csv"))
  }
  optimise.bayes.data1 <- ldply(file.list,read.optimise.bayes.data1)
  optimise.bayes.data1$SET <- SET
  optimise.bayes.data1$STUDY <- 4

# Read in the optimise.bayes2 simulation data (10 mg/kg initiation)
  read.optimise.bayes.data2 <- function(file.list) {
    optimise.bayes.data2 <- read.csv(file = paste0(project.dir,file.list,"/optimise_bayes_data2.csv"))
  }
  optimise.bayes.data2 <- ldply(file.list,read.optimise.bayes.data2)
  optimise.bayes.data2$SET <- SET
  optimise.bayes.data2$STUDY <- 5

# Bind all data frames together
  all.data <- rbind(label.data,clinical.data,clinical.TDM.data,optimise.bayes.data1,optimise.bayes.data2)
  all.data <- all.data[all.data$time <= 546,] # Remove NA rows
  all.data$IPRE <- as.numeric(all.data$IPRE)
  all.data$STUDY <- as.factor(all.data$STUDY)

# For each individual calculate when doses were given and how much
  ind.summary.function <- function(all.data) {
    ind.summary.data <- data.frame(
      time = all.data$time[all.data$amt != 0],
      amt = all.data$amt[all.data$amt != 0],
      int = c(0,diff(all.data$time[all.data$amt != 0])),
      IPRE = all.data$IPRE[all.data$amt !=0],
      ADA = all.data$ADA[all.data$amt != 0],
      ALB = all.data$ALBCOV[all.data$amt != 0],
      WT = all.data$WTCOV[all.data$amt != 0],
      "mg/kg" = all.data$amt[all.data$amt != 0]/all.data$WTCOV[all.data$amt != 0]
    )
  }
  ind.summary.data <- ddply(all.data, .(STUDY,SET,SIM,ID), ind.summary.function)

# Subset all.data for everyone's trough data
  collect.trough.function <- function(all.data) {
    # Subset ind.summary.data for the specific individual
      ID.number <- all.data$ID[1]
      SET.number <- all.data$SET[1]
      SIM.number <- all.data$SIM[1]
      STUDY.number <- all.data$STUDY[1]
      trough.times <- ind.summary.data$time[ind.summary.data$ID == ID.number & ind.summary.data$SIM == SIM.number & ind.summary.data$SET == SET.number & ind.summary.data$STUDY == STUDY.number]
    # Subset all.data for times in trough.times
      collect.trough.data <- all.data[all.data$time %in% trough.times,]
  }

  collect.trough.data <- ddply(all.data, .(STUDY,SET,SIM,ID), collect.trough.function)
```

## Plot concentration-time for all studies

Represented as median and 95% prediction intervals

```{r,echo = TRUE,warning = FALSE}
# Line (median) and ribbon (prediction intervals)
  # Calculate
    summary.data <- ddply(ind.summary.data, .(STUDY,time), function(ind.summary.data) summary.function(ind.summary.data$IPRE))

  # Assign descriptions to STUDY
    summary.data$STUDYf <- as.factor(summary.data$STUDY)
    levels(summary.data$STUDYf) <- c("Label","Clinical","Clinical TDM","Bayes - 5mg/kg Init","Bayes - 10mg/kg Init")

  # Plot
    plotobj1 <- NULL
    plotobj1 <- ggplot(summary.data)
    plotobj1 <- plotobj1 + geom_line(aes(x = time,y = median,colour = STUDY))
    plotobj1 <- plotobj1 + geom_ribbon(aes(x = time,ymin = stat.95lo,ymax = stat.95hi,fill = STUDY),alpha = 0.3)
    plotobj1 <- plotobj1 + geom_hline(aes(yintercept = trough.target),linetype = "dashed")
    plotobj1 <- plotobj1 + geom_hline(aes(yintercept = trough.upper),linetype = "dashed")
    plotobj1 <- plotobj1 + scale_x_continuous("\nTime (days)",breaks = c(0,14,42,98,154,210,266,322,378,434,490,546))
    plotobj1 <- plotobj1 + scale_y_log10("Infliximab Concentration (mg/L)\n",breaks = c(0.0001,0.001,0.01,0.1,1,10,100,1000),labels = c(0.0001,0.001,0.01,0.1,1,10,100,1000))
    # plotobj1 <- plotobj1 + scale_y_continuous("Infliximab Concentration (mg/L)\n",lim = c(0,NA))
    plotobj1 <- plotobj1 + facet_wrap(~STUDYf)
    plotobj1 <- plotobj1 + theme(legend.position = "none")
    print(plotobj1)
```

## Plot weight and albumin over time

```{r,echo = TRUE,warning = FALSE}
# Weight
# Line (median) and ribbon (prediction intervals)
  # Calculate
    collect.trough.data$cWT <- collect.trough.data$WTCOV-collect.trough.data$BASE_WT
    wt.summary.data <- ddply(collect.trough.data, .(STUDY,time), function(all.data) summary.function(all.data$cWT))

  # Plot
    plotobj2 <- NULL
    plotobj2 <- ggplot(wt.summary.data)
    plotobj2 <- plotobj2 + geom_line(aes(x = time,y = median,colour = STUDY))
    plotobj2 <- plotobj2 + geom_ribbon(aes(x = time,ymin = stat.95lo,ymax = stat.95hi,fill = STUDY),alpha = 0.3)
    plotobj2 <- plotobj2 + scale_x_continuous("\nTime (days)")
    plotobj2 <- plotobj2 + scale_y_continuous("Change in total body weight (kg)\n")
    # plotobj2 <- plotobj2 + scale_y_continuous("Infliximab Concentration (mg/L)\n",lim = c(0,NA))
    plotobj2 <- plotobj2 + facet_wrap(~STUDY)
    plotobj2 <- plotobj2 + theme(legend.position = "none")
    print(plotobj2)
    
# Albumin
# Line (median) and ribbon (prediction intervals)
  # Calculate
    collect.trough.data$cALB <- collect.trough.data$ALBCOV - collect.trough.data$BASE_ALB
    alb.summary.data <- ddply(collect.trough.data, .(STUDY,time), function(all.data) summary.function(all.data$cALB))

# Plot
  plotobj3 <- NULL
  plotobj3 <- ggplot(alb.summary.data)
  plotobj3 <- plotobj3 + geom_line(aes(x = time,y = median,colour = STUDY))
  plotobj3 <- plotobj3 + geom_ribbon(aes(x = time,ymin = stat.95lo,ymax = stat.95hi,fill = STUDY),alpha = 0.3)
  plotobj3 <- plotobj3 + scale_x_continuous("\nTime (days)")
  plotobj3 <- plotobj3 + scale_y_continuous("Change in albumin (U/L)\n")
  # plotobj3 <- plotobj3 + scale_y_continuous("Infliximab Concentration (mg/L)\n",lim = c(0,NA))
  plotobj3 <- plotobj3 + facet_wrap(~STUDY)
  plotobj3 <- plotobj3 + theme(legend.position = "none")
  print(plotobj3)
```

## Proportion of time spent under the target trough concentration (3 mg/L)

```{r,echo = TRUE,warning = FALSE}
# Calculate median and percentiles for AUT at 546 for all studies
  ptut.summary.data <- ddply(all.data, .(STUDY,time), function(all.data) summary.function(all.data$pTUT))

# Plot
  plotobj4 <- NULL
  plotobj4 <- ggplot(ptut.summary.data)
  plotobj4 <- plotobj4 + geom_line(aes(x = time,y = median,colour = STUDY))
  plotobj4 <- plotobj4 + geom_ribbon(aes(x = time,ymin = stat.95lo,ymax = stat.95hi,fill = STUDY),alpha = 0.3)
  plotobj4 <- plotobj4 + geom_hline(aes(yintercept = 0.1),linetype = "dashed")
  plotobj4 <- plotobj4 + scale_x_continuous("\nTime (days)")
  plotobj4 <- plotobj4 + scale_y_continuous("Proportion of time spent under target trough\n")
  # plotobj4 <- plotobj4 + scale_y_continuous("Infliximab Concentration (mg/L)\n",lim = c(0,NA))
  plotobj4 <- plotobj4 + facet_wrap(~STUDY)
  plotobj4 <- plotobj4 + theme(legend.position = "none")
  print(plotobj4)
```

## Proportion of individuals with ADA present

```{r,echo = TRUE,warning = FALSE}
# Calculate median and percentiles for AUT at 546 for all studies
  ada.summary.data <- ddply(all.data, .(STUDY,time), function(all.data) sum(all.data$ADA))
  names(ada.summary.data)[3] <- "nADA"
  ada.summary.data$pADA <- ada.summary.data$nADA/(n*nsim*nset)

# Plot
  plotobj5 <- NULL
  plotobj5 <- ggplot(ada.summary.data)
  plotobj5 <- plotobj5 + geom_line(aes(x = time,y = pADA,colour = STUDY))
  plotobj5 <- plotobj5 + scale_x_continuous("\nTime (days)")
  plotobj5 <- plotobj5 + scale_y_continuous("Proportion of individuals with ADA present\n")
  # plotobj5 <- plotobj5 + scale_y_continuous("Infliximab Concentration (mg/L)\n",lim = c(0,NA))
  plotobj5 <- plotobj5 + facet_wrap(~STUDY)
  plotobj5 <- plotobj5 + theme(legend.position = "none")
  print(plotobj5)
```

## Summary of findings

```{r,echo = TRUE,warning = FALSE}
# Set up folder to save the processed output
  save.dir <- "/Volumes/Prosecutor/PhD/InfliximabBayes/infliximab-bayes-plots/"
  sim.output.dir <- paste0("SIM",nsim,"_IND",n)
  dir.create(file.path(paste0(save.dir,sim.output.dir,"/")),showWarnings = FALSE)
```
